### ISSUE TITLE
tech_review: Web Assembly

### ISSUE THREAD

**Issue by voglerdaniel** [uwescience/WaterReuseDSSG2024#114]
Read up on Web Assembly & how we can use it to deploy local computational resources for our final project website

**Comment by atkissoncj** [comment]
https://blog.djnavarro.net/posts/2023-04-09_webr/
https://github.com/djnavarro/webr-automata
https://laderast.github.io/webr-demo/#/title-slide
https://www.tidyverse.org/blog/2024/04/webr-0-3-1/
https://www.nienxiangtou.com/posts/webr/ (webr + quarto)
https://github.com/r-wasm/webr/?tab=readme-ov-file
https://docs.r-wasm.org/webr/latest/

**Comment by atkissoncj** [comment]
Here's a thing about WebR: Not all packages can be run on it. *Many of these issues* come from packages that are downloading data from somewhere. This happens because many of those are using sockets, but since WebAssembly is through js, all of those need to be FETCHs, instead. So that breaks. Also, we can't compile from source, meaning that things like BioConductor aren't available (since BioConductor is almost an alternative repository system to CRAN).

Here are the packages that I found dependencies for in our code, if they're available, and what is preventing it.

package - if available for WebR - package that is preventing it

tigris - NO - curl
sf - yes
XXX tidyverse - NO - curl
usmap - yes
readxl - yes
toxpiR - NO - S4Vectors, BiocGenerics
tidycensus - NO - curl
raster - yes
terra - yes
urbnmapr - not on CRAN



ALL TIDYVERSE packages are supported, just not tidyverse
ggplot2 - yes
dplyr - yes
tidyr - yes
readr - yes

**Comment by voglerdaniel** [comment]
Done
