### ISSUE TITLE
chore: Create user stories

### ISSUE THREAD

**Issue by atkissoncj** [uwescience/WaterReuseDSSG2024#3]
I'd like to build off of Dave Beck's workshop on software design by having us immediately start thinking about use cases. To that end, let's have each of you *independently* write 5 user stories for what we're working on this summer. Please keep those private and post them here on Mon 7/1 before the team meeting. I'd like to talk about those on Monday at the team meeting.

**Comment by voglerdaniel** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-f102167d-7fff-735c-9981-c78c994ce052"><div dir="ltr" style="margin-left:0pt;" align="left">
User | Background | Usage of our Product | Desired Features | Technical Understanding/Capacity
-- | -- | -- | -- | --
Water Reuse Advocate | Environmental advocate/lobbyist with an understanding of data analysis | Identify areas nationwide with high potential for water reuse to target advocacy efforts and research funding (e.g. Julie Minton’s role) | Intuitive interface, visualizations, filtering/sorting, exportable reports. | Basic: Comfortable with web-based tools, not coding. May have high technical skill & deep subject matter expertise, but probably a senior stakeholder without time for detailed data analysis. Wants the bottom line
Utility Manager | Utility manager overseeing water supply and wastewater treatment, with solid technical skills and detailed domain knowledge | Identify whether the jurisdiction covered by their utility has water reuse potential, optimize resources, and develop water reuse strategies. | Detailed analytics, customizable dashboards & maps, scenario planning tools (e.g. customizable assumptions, as we discussed). Ability to access raw data for analysis by others in their org. | High: Likely Proficient with data analysis and technical systems. However, time to engage in detail with data is likely low.
Policymaker (Aide) | Policy aide to a state/local government official responsible for research into policy on water resource management, with moderate technical skills. | Identify regions for water reuse investments and support policy recommendations. | Detailed data analysis, comparative analysis, scenario analysis (option to tweak assumptions, as we discussed) | Intermediate: Moderately comfortable with data analysis, but prefers spreadsheets to code.
University Water Researcher | University researcher studying water management and sustainability, with advanced technical skills. | Conduct in-depth analyses and publish research papers. | Access to raw data, advanced filtering/sorting, detailed documentation of cleaning and analysis pipeline, export options in various formats | High: Proficient in data analysis, statistical software like R, and probably GIS tools.
Urban Planner | Urban planner developing sustainable urban strategies to provide recommendations to a body like a city council or water board | Incorporate water reuse potential into policy recommendation documents | Interactive maps, impact modeling tools, collaboration features, user-friendly interface with tutorials. A format that is easy to export and incorporate into non-web formats | Intermediate: Familiar with basic GIS tools like storymaps (but not building them) and basic data analysis (spreadsheets, not code).

</div><br /></b>

**Comment by atkissoncj** [comment]
@voglerdaniel can you remove the last comment? I want everyone to develop their own independently, and then we can add them on Monday.

**Comment by Jihyeonbae** [comment]
Dave is an undergraduate student at the UW studying sociology. He wants to create campus accessibility index by incorporating multiple social and structural factors into account. He is searching for similar work process for creating a new synthetic index. He took introduction to statistics and has some coding experience in R. He has heard about dimensionality reduction, but isn’t fully confident. 

Minji is a graduate student studying political science. She wants to use the water equity index to write her dissertation. She wants to understand the substantive implication of indicators that were used to create the index. She understands basics of PCA, but does not have coding experience. 

Anurag, King county manager, received a petition from a local association of businesses asking for a relocation of wastewater discharge further North, away from the current discharge point. He wants to persuade local business people that implementing reuse add-ons instead of relocating it can significantly reduce wastewater management. Local businesses are not convinced. Anurag is searching for an intuitive visualization that he can show to people with no background in civil engineering nor data science.

Mark is a manager of the water treatment facility. He heard about water reuse from his colleagues and ran into water reuse benefit index online. With a background in environmental engineering, Mark intends to use the index to assess potential cost savings and environmental impacts associated with adopting water reuse technologies.

Sarah is a city planner tasked with developing a sustainability index for her city's urban development projects. She aims to integrate environmental, social, and economic factors into a comprehensive index that can guide future city planning decisions. Sarah has a background in urban planning and some familiarity with statistical analysis. She is particularly interested in understanding how to weight different indicators and wants to explore methods. Sarah is looking for practical examples and best practices from similar projects to ensure her sustainability index is robust.

**Comment by npovejsil** [comment]
Lindsey is a graduate student studying potential solutions to water scarcity crises in the United States at an acclaimed research university. She has recently learned about water reuse as a potential option to alleviate water supply challenges. She wants to use this index and our map to explore both the motivations behind implementing water reuse and the general areas of the U.S. she should prioritize in her research. She is keeping a broad frame of reference for water scarcity solutions and is interested in getting the big picture ideas for water reuse.

Mr. Jones is an EPA official who reviews grant proposals for water research. He recently heard of our index and map and is curious to see what it’s all about. He’s deeply familiar with EPA-funded research projects and wants to see how our tool contributes to the field. Mr. Jones is not technical at all, and he’s not great with user interfaces as he’s used to reading report-style information. He would love to learn if he should be prioritizing water reuse research going forward.

Cindy is a DSSG fellow in the 2024 summer cohort. Her background knowledge of water reuse consists of Miriam’s Water 101 presentation during the first week of the program. She wants to check out what the Water Reuse team has been up to for the past 10 weeks and is interested in clicking around the website to learn about our goals and methodology, as well as our final project. She has been on a similar style of project and has some insight into good research methods and statistics. In general, she’s slightly critical/judgmental, so she’s going into the exercise looking for flaws in our design.

Adrienne is a professional engineer in the drinking water treatment industry. She has first-hand knowledge of how slow-moving the field is and wants to be a part of the push for innovation and sustainability measures. She is searching on the internet for any interesting new research and comes across our index and map. She wants to use our visualizations and index measures as a part of a presentation she is giving at a conference.

Guy is an environmental justice activist and organizer. He is deeply passionate about water access equity in the United States. He doesn’t know anything about the mechanics of water reuse but is interested in on-site reuse and how it might allow communities to have more control over their water supplies. He’s looking into how our index includes equity factors to learn about areas to prioritize for raising water reuse awareness as a tool to achieve water access equity.

**Comment by Mbye20** [comment]
1.	Daniel is an EPA employee. He needs an interface that he can use to find locations that need water reuse facilities the most. He wants an interactive interface that he uses to study and understand the need for water reuse infrastructure in various places in the US. He has little technical skills.
2.	Aisha is a utility employee considering expanding into the water reuse area. She wants to see places that are in dire need of water reuse. She needs an interactive application that she can use to visually see these places and give valuable recommendations to her company. She does not have high technical skills.
3.	Mariama is a community member. She heard about water reuse and is interested in it. She wants to learn more about it. She wants a less complicated and easy-to-understand web application interface that she can easily use to view the water reuse needs of different US counties and the reasons for this need. She has no technical knowledge.
4.	Betty is an employee at XYZ Water Reuse consultancy firm. One of the consultancy clients is a utility company that is considering establishing a water reuse facility. Betty wants a credible interactive index web application that she can use to view places in absolute need of water reuse facilities and the profitability potential of these facilities. She has technical and industrial knowledge.
5.	Ida is a researcher. She wants to build a water reuse feasibility index, where she can incorporate the economic (economic and financial analysis), environmental and technical feasibility. She wants a water reuse index to use as a baseline tool and sample to build this analysis. She is technically competent.

**Comment by miriamhacker** [comment]
WOW - these are great!

**Comment by Mbye20** [comment]
1.	Daniel is an EPA employee. He needs an interface that he can use to find locations that need water reuse facilities the most. He wants an interactive interface that he uses to study and understand the need for water reuse infrastructure in various places in the US. He has little technical skills.
2.	Aisha is an employee of a utility company that is considering expanding into the water reuse area. She wants to see places that are in dire need of water reuse. She needs an interactive application that she can use to visually see these places and give valuable recommendations to the company. She does not have high technical skills.
3.	Mariama is a community member. She heard about water reuse and is inspired by it. She wants to learn more about it. She wants a less complicated and easy-to-understand web application interface that she can easily use to view the water reuse needs of different US counties and the reasons for this need. She has no technical knowledge.
4.	Betty is an employee at XYZ Water Reuse consultancy firm. One of the consultancy clients is a utility company that is considering establishing a water reuse facility. Betty wants to build a credible interactive web application index that she can use to view places in absolute need of water reuse facilities and the profitability potential of these facilities. She has technical and industrial knowledge.
5.	Ida is a researcher. She wants to build a water reuse feasibility index, where she can incorporate economic, environmental, and technical feasibility measures. She needs a tool that she can use to create a feasibility index and display them on an interactive web application. She is technically competent.
6.	Mbye is an employee at the Gambia National Water and Electricity Company (NAWEC). The company is planning to build an index that will help them identify the regions in need of wastewater treatment facilities. As the analyst at the company, he needs a tool that he can use to create the index and display it on an interactive web application. He has years of experience working with data and R.

**Comment by npovejsil** [comment]
Carolyn is a researcher in the water sector. She is interested in creating and mapping a water reuse index for benefit potential. She wants to gain valuable insights about specific geographic areas and populations that should be prioritized based on specific environmental and infrastructure drivers. She is a technical person who codes in R, can clean datasets and wants to deliver valuable insights to stakeholders. 

Nora is a grad student. She thinks it would be fun to map cities in the U.S. based on their concentration of artisanal coffee shops. She can clean data and easily code this herself but wants to test out if our website works and make a fun map to share with her friends. 

James is a future DSSG student who is working on a mapping and index creation project. His team wants to fork our repo and build off of it to meet their specific needs (their data expands beyond the continental United States). He has technical capability but would love to follow an existing process to guide him. 

Miriam is not a Data Scientist but would be interested in creating a water reuse index and mapping it to present to stakeholders. She has access to clean datasets and an understanding of the columns she wants it to be calculated from. She doesn't know how to choose the weights or compiling method (PCA, archetypal analysis, etc.). 

Jessie works at a non-profit organization that deals with hunger in the U.S., and she somehow heard about our website. She thinks that with the right datasets, she might be able to map the highest-hunger areas of her region. She has no idea how to do anything data-related but hopes she'll be able to figure it out to make a visualization for her grant proposals.

**Comment by voglerdaniel** [comment]
User | Background | Usage of our product | Desired Features | Technical Understanding/Capacity
-- | -- | -- | -- | --
Water reuse researcher (Carolyn) | Carolyn researches water reuse; wants to create index quantifying potential for reuse across US counties | Provide cleaned datasets; use output to map index, make a visualization of that input (map) available to nontechnical users via a website | Ability to load datasets; checks notifying whether datasets are in format that GeoNDXR can work with; clear functions & workflow to output HTML pages; clear user guide specifying her options with the output | High, focused in R; wants streamlined features to enable focus elsewhere (she doesn’t want to do web dev)
Data journalist | Sarah is a data journalist for a major media company; she supports traditional journalists who want to supplement stories comparing regions in the US with data | Provide cleaned datasets; use output to map index, make a visualization of that input (map) available to nontechnical users via a website | Ability to load datasets; checks notifying whether datasets are in format that GeoNDXR can work with; clear functions & workflow to output HTML pages; clear user guide specifying her options with the output; ability to customize output; transparently explain how indices are calculated | High; focused in R; wants streamlined workflow for index generation but also needs flexibility
Economic policy analyst | Mike is an economic policy analyst for a think tank. He wants to create a regional index displaying how a custom inflation metric has risen differently across parts of the US | Provide cleaned datasets; use output to map index, make a visualization of that input (map) available to nontechnical users via a website | Ability to load datasets; checks notifying whether datasets are in format that GeoNDXR can work with; clear functions & workflow to output HTML pages; clear user guide specifying her options with the output; ability to customize output; transparently explain how indices are calculated | High; focused in R; wants streamlined workflow for index generation but also needs flexibility
Climate policy researcher | Joe is a climate policy researcher at a university. He wants to aggregate different climate risk, produce an index, and make a visualization available to nontechnical users on his Github to showcase his work | Provide cleaned datasets; use output to map index, make a visualization of that input (map) available to nontechnical users via a website | Ability to load datasets; checks notifying whether datasets are in format that GeoNDXR can work with; clear functions & workflow to output HTML pages; clear user guide specifying her options with the output; ability to customize output; transparently explain how indices are calculated | High; focused in R; wants streamlined workflow for index generation would like flexibility in display options, but wants optimization for Github
Data science job market candidate | Daniel is a data science master’s student looking for jobs when he graduates. He is interested in aggregating different metrics, e.g. election polling results, to make predictions about elections. He wants to create an index to predict each congressional district’s outcome in the presidential election (based on more than just polls) and make a clean visualization available on Github to showcase his work | Provide cleaned datasets; use output to map index, make a visualization of that input (map) available to nontechnical users via a website | Ability to load datasets; checks notifying whether datasets are in format that GeoNDXR can work with; clear functions & workflow to output HTML pages; clear user guide specifying her options with the output; ability to customize output; transparently explain how indices are calculated | High; focused in R; wants streamlined workflow for index generation would like flexibility in display options, but wants optimization for Github

**Comment by Jihyeonbae** [comment]
Jon is a journalist at the NYT, leading Climate Change section. He wants to write an article that argues that people should consider the temperature of crosswalk, streets, and public facilities when measuring "heat wave risk" index, on top of air temperature. Seeing none of the relevant index, Jon wants to create his own. He ultimately wants to put a well-visualized US choropleth for the NYT readers. He has received his BA in Communication 10 years ago and has not taken any data-science class. 

Beth is an intern at the NYT, working for Jon. Jon assigned her with a task of creating a US map at the County level based on the variables that he wants to include for the index creation. She is looking for any existing R repo so that she doesn't have to reinvent the wheel. She only has 2 days to finish this task. She also wants to create many different versions of the same plot, by tweaking a few details. She recently got her MS in data science and has much experience in R coding. 

Omar is working for a local environment NGO in Houston. He wants to persuade local governor to appropriate more budget on climate change efforts. He came across an article with a map that shows Houston ranked the first in climate change vulnerability. He is planning to prepare a PPT slide with that map on. He is hoping to get not just the map but the ranking table so that he can directly show the numbers to the governor. Omar does not have any coding skills. 

Jihyeon is a political science student at the UW. She is preparing for conference presentation slides. She is hoping to visualize the political violence index that she created. She came across the visualization tool that maps US county data. She tries to change the code so that she can crosswalk maps from country to continents, and map her index on the global map with different geospatial scales.

**Comment by atkissoncj** [comment]
Kendrick is a journalist working for 538. He wants to be able to show the relationship between an index that he is interested in (industrial jobs) and changes in polling in the presidential race since JD Vance was nominated as VP. He would like to be able to overlay an explorable index and a different variable so that the geographical relationship becomes obvious. He is a proficient technical user with experience cleaning data but a busy journalist.

Suzannah is a college student with a slight smartphone addiction. She got really upset that Seattle wasn't the "most livable" city in the recent Zillow livability index and wants to know what factors were included and how that would change if there were different factors included. She would like to be able to save her index that shows Seattle to be the most livable city. She spends most of her time at a lab bench and isn't very familiar with data analysis, except for that one stats class everyone had to take.

Zach is a researcher studying a new way to learn about homelessness that he thinks will work best in areas of a certain type. He would like to quickly throw in some census data and find places similar to and different from Seattle to test this new process. He wants to be able to use that as a part of a grant application. He is highly technically proficient.

Aneesha is a program officer at NSF. They are worried that people applying to their program are not up-front about how their site sampling strategies. They would like people to provide the evidence they use to select sites in a way that is easy for them to see sites that are similar and different in order to see if their sampling strategy is biased. They really want to know the effect of including a subset of the selection variables on the sampling strategy. They are technically proficient, but it has been a few years and, besides, they're way too busy.

Curtis is a data scientist at eScience Institute. He would like to be able to build some cool tech that he can teach to other technical people at the eScience Institute in order to make their work better. This means that he needs a fully functioning pipeline that does something nifty and is well-written both in code and comments. He's super technically proficient.

**Comment by chayek** [comment]
Jackie is a technical assistance provider at the Rural Water Association. She wants to know where water reuse could provide benefits in her jurisdiction so that she can raise the topic with water utility managers when they have discussions.  She wants to be able to zoom the map of the index to her region and click on different communities to see their individual scores while she is in the office. She wants to understand where the benefits are coming from so she can explain it better to others.  She would also like to download a table of index scores that she can have with her in the field when she has limited internet access. 

Rhonda is a political scientist that studies environmental policies across the country.  She saw our index and wants to use the ecosystem protection slice values in one of her analyses as an explanatory variable for different kinds of policies. She is not really interested in the mapping capabilities, she wants to be able to access the data.  She is used to working with datasets.

Jason is a State Revolving Fund administrator evaluating funding applications for water reuse projects.  He wants to use our index to rank applicants by the potential overall benefit so the state can get the most bang for their buck. He needs to be able to search for the overall index value for a specific community, as well as for the benefit towards individual drivers.  

John is a utility manager that is trying to figure out how to meet growing infrastructure needs in his community.  All decisions need to be approved by his board.  He is curious to compare water reuse to other options, but he needs the board to approve funding for conducting a feasibility assessment.  He isn't much of a programmer and isn't used to interpreting indices. He wants to pull some of the numbers that went into our index (before they were combined) to do a back-of-the-envelope calculation that he can bring to the board.
