### ISSUE TITLE
bug: maps not showing up correctly

### ISSUE THREAD

**Issue by chayek** [uwescience/WaterReuseDSSG2024#86]
It ran all the way through (victory!). Unfortunately, the map came out like this: 

![NDC2NDI](https://github.com/uwescience/WaterReuseDSSG2024/assets/20246563/04f5bc00-aed3-46a9-9dfa-79fd94ec6d55)

This looks like the issue that @voglerdaniel was having a while back. Easy fix?

**Comment by Mbye20** [comment]
@chayek  the output is like that because the shapefile is not cropped to include only the continental US.
I got a better graph when I used this code to filter the shapefile to include only the continental: shapefile <- tigris::counties(year = 2023, filter_by = c(-124.7844079, -66.9513812, 24.7433195, 49.3457868)). You may need to update the bounding box above that I used to filter the shapefile.
![image](https://github.com/uwescience/WaterReuseDSSG2024/assets/78307266/922c5a43-3566-428c-b472-aa598ae11a39)

**Comment by Mbye20** [comment]
close with #111
