### ISSUE TITLE
feat: Cut datasets to our eligible map scale

### ISSUE THREAD

**Issue by atkissoncj** [uwescience/WaterReuseDSSG2024#93]
If we're only requiring this to work in the continental US, then we could put a step in mapper that cuts data down to only the eligible data.

**Comment by voglerdaniel** [comment]
If I remember correctly @Mbye20 has done a version of this for the contiguous (lower 48) US states by hard-coding coordinates in a notebook. Mbye, if you can share that code snippet here I will turn it into a function with constants and adjust those to so that they filter all US states, not just lower 48.
